export * from './footer/Footer'
export * from './header/Header'
export * from './input/Input'
export * from './Button/Button'
export * from './H2/H2'
export * from './Search/search'
export * from './Error/Error'
export * from './Error-message-in-auth-or-register/ErrorMessage'